@extends('layouts.app')
@section('title', 'About Us')
@section('content')
<section class="about-hero"><div><p class="eyebrow">THE IDEA BEHIND HOMESERVICES</p><h1>Better connections.<br><span>Better cared-for homes.</span></h1><p class="lead">From an everyday repair to a fresh start for your space, find local professionals and choose the help that fits your home.</p><div class="hero-actions"><a class="button" href="{{ route('services') }}">Explore services ↗</a><a class="button secondary" href="{{ route('register', ['role' => 'provider']) }}">Join as a professional</a></div></div><div class="about-hero-art" aria-hidden="true"><div class="about-house">⌂</div><span class="about-art-label">A little help. A better home.</span><div class="about-art-icons"><x-icon name="Electrical" /><x-icon name="Plumbing" /><x-icon name="Gardening" /></div></div></section>
<section class="about-purpose"><div><p class="eyebrow">OUR PURPOSE</p><h2>Connecting homes<br>with skilled hands.</h2></div><div><p>Finding a professional can mean asking around, comparing different contacts and trying to work out who covers your area. HomeServices brings those details together so you can make a more informed choice.</p><p>Our goal is to give householders a straightforward way to discover help, and give service providers a place to introduce their skills, share their availability and connect with potential customers.</p><p class="about-project-note">HomeServices is a university software engineering project being developed in stages. This version focuses on professional discovery, direct contact and customer feedback.</p></div></section>
<section class="section about-services"><x-section-heading eyebrow="CARE FOR EVERY CORNER" title="One place for everyday home needs" /><p class="about-section-lead">Explore six service categories, then browse the professionals registered for the work you need.</p><div class="about-service-types">@foreach(['Electrical', 'Plumbing', 'Cleaning', 'Painting', 'AC Repair', 'Gardening'] as $service)<span><x-icon :name="$service" />{{ $service }}</span>@endforeach</div><a class="text-link" href="{{ route('services') }}">Browse the service catalogue ↗</a></section>
<section class="about-audiences"><article><p class="eyebrow">FOR HOUSEHOLDERS</p><h2>Find the right help<br>with clearer information.</h2><p>Browse by service, check where a professional works and learn about their experience before getting in touch.</p><ul><li>Compare service areas, biographies and working hours.</li><li>See provider photos and their stated availability.</li><li>Call or open WhatsApp directly from a provider card.</li><li>Read ratings and share your experience with a customer account.</li></ul><a class="button" href="{{ route('register') }}">Create a customer account ↗</a></article><article><p class="eyebrow">FOR PROFESSIONALS</p><h2>Your skills deserve<br>a clear introduction.</h2><p>Create a professional profile that helps customers understand what you offer and when they can reach you.</p><ul><li>Select the service categories that match your work.</li><li>Add your location, experience, contact details and photo.</li><li>Update your available, working or unavailable status.</li><li>Build your profile with customer ratings and feedback.</li></ul><a class="button secondary" href="{{ route('register', ['role' => 'provider']) }}">Register as a provider ↗</a></article></section>
<section class="section"><x-section-heading eyebrow="HOW IT WORKS" title="From finding a service to starting a conversation" /><div class="about-steps"><article><span>01</span><h3>Choose your service</h3><p>Start with the category that matches the help your home needs.</p></article><article><span>02</span><h3>Explore professionals</h3><p>Compare profiles, locations, experience and customer reviews.</p></article><article><span>03</span><h3>Discuss the details</h3><p>Contact your chosen provider to agree on timing, scope and price.</p></article><article><span>04</span><h3>Share your experience</h3><p>After using the service, leave a rating and optional review. You can update it later.</p></article></div></section>
<section class="about-transparency"><div><p class="eyebrow">CLEAR EXPECTATIONS</p><h2>Useful details.<br>Informed decisions.</h2><p>We want the information on each profile to help you decide what to ask before arranging a service.</p></div><div class="about-transparency-items"><article><h3>Provider-managed profiles</h3><p>Experience, service area and work status are supplied by providers. Availability is their saved status, so confirm the timing directly.</p></article><article><h3>Customer feedback</h3><p>Logged-in customers can leave one rating per provider and update it. Reviews are not yet linked to verified completed bookings.</p></article><article><h3>Platform oversight</h3><p>Administrators manage service categories and can suspend or reactivate accounts. Suspended providers are hidden from the public directory.</p></article></div></section>
<section class="section about-roadmap"><div><p class="eyebrow">GROWING STEP BY STEP</p><h2>What you can use today.</h2><p>Browse services, discover providers, make direct contact, manage your profile and share reviews.</p></div><div><span class="about-next-label">PLANNED NEXT</span><h3>A more complete service journey</h3><p>In-app bookings, messaging, payments and complaint handling are not available in this version. Arrange service details directly with your provider.</p></div></section>
<x-cta />
@endsection
