@extends('layouts.app')
@section('title', 'Admin dashboard')
@section('content')
<section class="dashboard-header admin-dashboard-hero"><p class="eyebrow">ADMIN WORKSPACE</p><h1>Your platform at a glance.</h1><a class="button secondary" href="{{ route('profile.edit') }}">Edit profile</a><p class="lead">Monitor accounts, services and customer feedback.</p><a class="button" href="{{ route('admin.categories.index') }}">Manage service categories ↗</a></section>
@if(session('status'))<p class="profile-save-notice" role="status">{{ session('status') }}</p>@endif
<div class="admin-stat-grid">@foreach($stats as $label => $count)<div class="admin-stat"><p>{{ $label }}</p><strong>{{ $count }}</strong></div>@endforeach</div>
<div class="admin-chart-grid">@foreach($charts as $title => $segments)<x-admin-pie-chart :title="$title" :segments="$segments" />@endforeach</div><p class="admin-chart-caption">Charts show all customer and provider accounts. Availability includes active providers with a professional profile. Account filters apply to the list below.</p>
<section class="panel admin-accounts"><h2>Customer & provider accounts</h2><p class="muted">Suspend an account to block access and hide its provider listing. Reactivate it when ready.</p>
<form class="admin-filters" method="GET" action="{{ route('admin.dashboard') }}"><div class="field"><label for="search">Name or email</label><input id="search" name="search" maxlength="100" value="{{ request('search') }}" placeholder="Search accounts"></div><div class="field"><label for="role">Account type</label><select id="role" name="role"><option value="">All accounts</option>@foreach(['customer','provider'] as $role)<option value="{{ $role }}" @selected(request('role') === $role)>{{ ucfirst($role) }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="suspended" @selected(request('status') === 'suspended')>Suspended</option></select></div><button class="button">Filter</button><a href="{{ route('admin.dashboard') }}">Reset</a></form>
<div class="admin-table-wrap"><table class="admin-account-table"><thead><tr><th>Account</th><th>Role</th><th>Status</th><th>Provider state</th><th>Action</th></tr></thead><tbody>@forelse($users as $user)<tr><td><div class="admin-account-person"><x-profile-photo :user="$user" /><div><strong>{{ $user->name }}</strong><span>{{ $user->email }}</span></div></div></td><td>{{ ucfirst($user->role->value) }}</td><td><span class="provider-status {{ $user->suspended_at ? 'is-unavailable' : 'is-available' }}">{{ $user->suspended_at ? 'Suspended' : 'Active' }}</span></td><td>{{ $user->providerProfile ? ($user->providerProfile->is_working ? 'Working' : ($user->providerProfile->is_available ? 'Available' : 'Unavailable')) : '—' }}</td><td><form method="POST" action="{{ route('admin.accounts.update', $user) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="{{ $user->suspended_at ? 'reactivate' : 'suspend' }}"><button class="button secondary" aria-label="{{ $user->suspended_at ? 'Reactivate' : 'Suspend' }} {{ $user->name }}">{{ $user->suspended_at ? 'Reactivate' : 'Suspend' }}</button></form></td></tr>@empty<tr><td colspan="5">No accounts match these filters.</td></tr>@endforelse</tbody></table></div>{{ $users->links() }}</section>

@endsection
